---
title: "Homework 3"
author: "Rachel Hall"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1 
First String,Second,1.22,3.4

Second,More Text,1.555555,2.2220

Third,x,3,124

**Answer:** 
```Find \s+\s ```

```Replace \,```

**Explanation:** Looking for multiple spaces and then replacing with just a comma.


### Question 2
Bryan Ballif (University of Vermont)

Aaron Ellison (Harvard Forest)

Sydne Record (Bryn Mawr)

**Answer:** 
```Find (\w+),\s(\w+),\s(\w+.*)```

```Replace \2 \1 \(\3\)```

**Explanation:** Creating three captures then switching the first and second leaving a space in between. For the third, adding parenthesis around. 


### Question 3
0001 Georgia Horseshoe.mp3

0002 Billy In The Lowground.mp3

0003 Winder Slide.mp3

0004 Walking Cane.mp3

**Answer:** 
```Find (mp3)(\s)```

```Replace \1\n```

**Explanation:** Finding mp3 and replacing the space after with a line break.

### Question 4
Georgia Horseshoe_0001.mp3

Billy In The Lowground_0002.mp3

Winder Slide_0003.mp3

Walking Cane_0004.mp3

**Answer:** 
```Find (\d{4}) (\w+.*)(.mp3)```

```Replace \2_\1\3```

**Explanation:** Capturing each portion of the line into three different captures for the four digit number, song title, and mp3. Then rearrange the captures accordingly with an underscore between the title and number. 


### Question 5

C_pennsylvanicus, 44

C_herculeanus, 3

M_punctiventris, 4

L_neoniger, 55


**Answer:** 
```Find (\w)\w+,(\w+),(\w.*),(\w+)```

```Replace \1_\2, \4```

**Explanation:** Capturing each portion of the line into four different captures. Then abbreviating for the first word and adding an underscore. Lastly, replacing the third capture with nothing to get rid of that portion of the lines.

### Question 6

C_penn, 44

C_herc, 3

M_punc, 4

L_neon, 55

**Answer:** 
```Find (\w)\w+,(\w{4})\w+,(\w.*),(\w+)```

```Replace \1_\2, \4``

**Explanation:** Similar to question 5, capturing each portion of the line but this time I used the quantifier to capture just the first four characters of the second capture. 

### Question 7

Campenn, 44, 10.2

Camherc, 3, 10.5

Myrpunc, 4, 12.2

Lasneon, 55, 3.3

**Answer:** ```Find (\w{3})\w+,(\w{4})\w+,(\w.*),(\w+)```

```Replace \1\2, \4, \3```


**Explanation:** Similar to the last two questions, capturing each portion of the line but this time I used the quantifier to capture the first three letters of the first capture and the first four characters of the second capture then combined the two captures into one word. Lastly, switching the third and fourth capture to switch their order. 
